# Generated by Django 4.2.5 on 2023-11-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articolo_options_alter_giornalista_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
